/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_ntb_inf_libusb_Libusb */

#ifndef _Included_ch_ntb_inf_libusb_Libusb
#define _Included_ch_ntb_inf_libusb_Libusb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    init
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ch_ntb_inf_libusb_Libusb_init
  (JNIEnv *, jclass);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    exit
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_exit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    setDebug
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_setDebug
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getDeviceList
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_ch_ntb_inf_libusb_Libusb_getDeviceList
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    freeDeviceList
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_freeDeviceList
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getBusNumber
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getBusNumber
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getPortNumber
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getPortNumber
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    unrefDevice
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_unrefDevice
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getPortNumbers
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getPortNumbers
  (JNIEnv *, jclass, jobject, jobject, jintArray);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getParent
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ch_ntb_inf_libusb_Libusb_getParent
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getVendorId
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getVendorId
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getProductId
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getProductId
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getNofConfigurations
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getNofConfigurations
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    open
 * Signature: (Ljava/nio/ByteBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ch_ntb_inf_libusb_Libusb_open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    close
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getDeviceAddress
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getDeviceAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getDeviceSpeed
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getDeviceSpeed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getActiveConfigDescriptor
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getActiveConfigDescriptor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getConfigValue
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getConfigValue
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getNofInterfaces
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getNofInterfaces
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getNofAltSettings
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getNofAltSettings
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getInterfaceNumber
 * Signature: (Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getInterfaceNumber
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getAlternateSetting
 * Signature: (Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getAlternateSetting
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getNofEndpoints
 * Signature: (Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getNofEndpoints
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getEndpointAddress
 * Signature: (Ljava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getEndpointAddress
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getMaxPacketSize
 * Signature: (Ljava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getMaxPacketSize
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getMaxIsoPacketSize
 * Signature: (Ljava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getMaxIsoPacketSize
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    claimInterface
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_claimInterface
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    releaseInterface
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_releaseInterface
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    bulkTransfer
 * Signature: (Ljava/nio/ByteBuffer;I[BII)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_bulkTransfer
  (JNIEnv *, jclass, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    resetDevice
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_resetDevice
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getTransferType
 * Signature: (Ljava/nio/ByteBuffer;IIII)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getTransferType
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getSerialNumberIndex
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getSerialNumberIndex
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getStringDescriptor
 * Signature: (Ljava/nio/ByteBuffer;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_ntb_inf_libusb_Libusb_getStringDescriptor
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getStringDescriptorAscii
 * Signature: (Ljava/nio/ByteBuffer;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_ntb_inf_libusb_Libusb_getStringDescriptorAscii
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getManufacturerDescIndex
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getManufacturerDescIndex
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    getProductDescIndex
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_ch_ntb_inf_libusb_Libusb_getProductDescIndex
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    relaseInterface
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_relaseInterface
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    setInterfaceAltSetting
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_ch_ntb_inf_libusb_Libusb_setInterfaceAltSetting
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     ch_ntb_inf_libusb_Libusb
 * Method:    openVidPid
 * Signature: (Ljava/nio/ByteBuffer;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_ch_ntb_inf_libusb_Libusb_openVidPid
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
